name: Build application and deploy from Main

on:
  push:
    paths:
    - 'QuizExperiment.Admin/**'
    - 'QuizExperiment.Models/**'
    - '.github/workflows/build_and_deploy_application.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Publish
      run: dotnet publish QuizExperiment.Admin/Server/QuizExperiment.Admin.Server.csproj -c Release -o website
    - name: Upload a Build Artifact (Website)
      uses: actions/upload-artifact@v2.2.2
      with:
        name: website
        path: website/**
        if-no-files-found: error
  deploy:
    needs: [build]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    
    env:
      LOCATION: canadacentral
      RESOURCEGROUP: yvr-quizzr
      PREFIX: jpquiz
      APPNAME: jpquiz-webapp
    steps:
    - name: Download a Build Artifact (Website)
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        name: website
        # Destination path
        path: website
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APPNAME }}
        slot-name: production
        package: website

    - name: az cli logout
      run: az logout
    
